### ISSUE TITLE
Exchange set catalogue - schema conformance

### ISSUE THREAD

**Issue by HolgerBothien** [iho-ohi/S-164-Sub-Group#29]
The catalog is not did not pass the schema validation:
Just one issue: an GML object needs to have an identifier, though no one will use it.
**`<gml:Curve>`** must be ammended to **`<gml:Curve gml:id="c1">`**
and each identifier must be unique because that is checked by the validator as well.
I have used the xerces validator but others will give the same result.

**Comment by rmalyankar** [comment]
Is it reporting any other errors (other than the absence of gml:id)?

**Comment by HolgerBothien** [comment]
I've got an error in the schema.
the import element for the S100 Part15 schema has a wrong path in the schemaLocation attribute.
I had to ammend it to: `../../../5.0.0/S100SE/20220728/Part15.xsd`
In general I would appreciate to get rid of the folders with the date.
They may have some use in an development environment but there is no reason to have them in the final release.
The version number is just enough and it is a possible cause of errors (as proved here).
I have found two more issues in the schema but they did not produce any error during the validation.

1. the element `<navigationPurpose>`  has no type assigned, though the type S100_NavigationPurpose itself is defined.
That means that any content of that element is conforming to the schema.
2. In S-100 Part 17 the model has the dataReplacement defined for S100_DatasetDiscoveryMetadata. I could not find an corresponding element in the schema.
Note that all of this findings are related to version 5.0 but may still exist in 5.1. At least I couldn't find any changes in the diff.

**Comment by rmalyankar** [comment]
The issues with Part15 xsd, navigationPurpose, and dataReplacement were fixed in the January 2023 distribution of Edition 5.0. If you were looking at the 5.1 diffs that is why the corresponding changes don't appear in the 5.1 diffs.

The OGC GML schemas included in the distribution will need to be updated at some point of time (for publication of 5.1?).  OGC updated the GML 3.2.1 schemas _folder_ on schemas.opengis.net but not the 3.2.1 _zip_.  Instead they made a 3.2.2 zip. Using 3.2.2 GML should fix the gml:id and polygon-curve issues. (Otherwise, the exchange catalog XML can be updated instead.)

**Comment by kusala9** [comment]
this can be closed if the issues are fixed in the 5.1 catalogues.
