### ISSUE TITLE
Staging/keys/AA00_DATA_PRODUCER

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-164-Sub-Group#37]
Dear All,

In S-101 Test Datasets repository, we also do the exercise to produce the S-164 test datasets .
In turn, we have to produce Exchange Set Catalogs and sign the dataset files.

Is it possible to use AA00_DATA_PRODUCER to sign  S101 test dataset repository  files ?

If yes,  I understand that I need the **private key** of the server "AA00_DATA_PRODUCER" to generate the signatures.

Have you missed to supply the private key ?  (or is it possible to deduce it from the supplied elements? ) 

Pol

**Comment by robertsandvik** [comment]
ECC and PRIMAR are developing an S-100ed5.1 SA Scheme Administrator application with agreed handover and training in mid-September. With this application in place it will be possible for IHO to issue Data Server Certificates compliant with S-100e5.1. They already have such functionality for issuing S-100e4 compliant Data Server certificates.

The reason why the S-100e4 and S-100e5.1 Data Server certificates are not compatible is because the certificate key lengths have increased from 1024 bits in S-100e4 to 2048 bits in S-100ed5/5.1.

If you are in a hurry to test this, you can create your own self signed certificates using the openssl commands found in S-100 part 15.

If you are looking for your own Data Producer codes, please follow the procedure on https://registry.iho.int/producercode/list2.do

**Comment by robertsandvik** [comment]
Good it worked out for you!
We have also experienced key length 2048 must be at the end of openssl command line. Part 15 need a minor update.

Also agree to your proposal to add an additional one-time task as you propose. The Data Server certificates will have to be renewed every 2 years. It will require that you generate a new .csr based on your original keypair and send it off to IHO. You can test it out in the middle of next month with IHO.

**Comment by kusala9** [comment]
Hi Pol, We can produce the signatures and certificates for the S-101 test datasets in S-164 and probably will based on the requirements of S-164 (we sometimes need to simulate unofficial producers, and data producer details) and we'll link them to the S-164 Scheme Administrator certificate too so don't produce these for the sake of S-164. the S-164 process will also create all the CATALOG.XML files and fields, all we need from this repository is the .000 and any supplementary files. It is useful to know which supplementary files are associated with which dataset files (and the CATALOG.XML is useful for that) but we can use the data in whatever form is easiest for you....

sorry, saw this yesterday but only just got chance to respond....

Jonathan. (S-164 subgroup)

**Comment by kusala9** [comment]
there are already other tests in S-164 for bad signatures, the LoadCorruptdata test is (in the current version) now 2.2.5 - We'll need to think of which scenarios to test for corrupt data I think - basically I think the corruption should be at the ISO8211 level, so truncate the file but ensure it's otherwise valid - so sign it and include in the exchange catalogue anyway. this test can then be a test that the ISO8211 can be parsed correctly.... I'm happy to do this though, the S-164 system we have will package the ENCs up fine so if you can give us the data file we'll create the exchange set.

**Comment by DavidGrant-NIWC** [comment]
This seems like an outdated test. How is the data getting corrupted? Presumably the exchange set creator validated the data prior to signing. If the data is signed and the signature matches, then the data should be good.
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/9637c0f2-ea6d-4873-9ce7-2a3549390b7a)

**Comment by kusala9** [comment]
it could be outdated and S-64 never defines what is meant by "corrupted". But there is a distinction between this one and corruption which invalidates the digital signature. I know producers are supposed to validate prior to signing but it is not inconceivable that a corruption sneaks in and a dataset which is corrupt is then signed. I think this test is really to ensure there is some protection on the ECDIS for such eventualities. We already test for datasets which don't conform to the FC, and also those which have unknown features/attributes so I figured the most likely remaining source of corruption is the 8211 layer - hence a truncated file.  I agree the data **should** be good but there are no guarantees....

**Comment by DavidGrant-NIWC** [comment]
My assumption is that this test is checking for corruption during transmission (such as over a serial line/modem), which was a problem in the late 1900's but should no longer be an issue.

**Comment by kusala9** [comment]
Suggest this is closed as the issue about keys is now fixed/superceded by events. If the "corrupt data" test is truly not required then it can be done under another issue. There is now a corrupt data test in the exchange sets which is a partial, corrupted dataset.
