### ISSUE TITLE
Content of CATALOG.XML

### ISSUE THREAD

**Issue by kusala9** [iho-ohi/S-164-Sub-Group#4]
It's not entirely clear which fields are "required" in CATALOG.XML as a minimum for correct operation of the ECDIS. This may be a long issue to fix as it will evolve as more testing is done by implementers.

* Coverage, Bounding Polygons (one per DataCoverage feature with min/max display scale) would seem to be required.
* S-98 Annex C should document which fields an OEM can reasonably expect to be present in each entry. 
* As these are discovered, they will need updating in S-98 and also all exchange sets will need to add appropriate values, including those already defined. 
* Should there be tests for the absence of these fields and SSE Codes in S-98 if they are not present?

**Comment by DavidGrant-NIWC** [comment]
The requirements are in S-100 17-4.5 and the individual product specs. I guess S-98 Annex C could make some elements mandatory that are optional in S-100.

* Coverage and bounding box are not required. I guess because some products may not be geographic. There should probably be a remark that `dataCoverage` is required for products which contain `dataCoverage` features.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/b25c67f1-bc61-447a-ab8a-840e61830d14)
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/04d25e07-c138-4c06-9bec-c2079c2a7156)

**Comment by kusala9** [comment]
agree. This would require an update in S-98 clarifying existence of DataCoverage for geographic datasets. as per previous comment. We need implementers opinion on whether this is "useful" or not though. The question for implementers is whether they want coverage/BB and max/min display scale in CATALOG.XML or whether they are content to retrieve from any datasets contained in the exchange set (bearing in mind exchange set might contain content which is unencrypted and which is inaccessible). On that basis we can decide how to take this forward and close the issue accordingly.

**Comment by DavidGrant-NIWC** [comment]
IMO, if a dataset is encrypted in the exchange set then the `boundingBox` or `dataCoverage` should be mandatory.

**Comment by kusala9** [comment]
I will add coverage to datasets for now. If the predominant view is they're not required (for unencrypted data) we can take them out. Maybe we should also leave some entries without coverage to check the ECDIS uses the dataset coverage in preference.

**Comment by kusala9** [comment]
Coverage Added to datasets now. If more fields are required we can do them on a case by case basis.
