### ISSUE TITLE
multiple datasets have `LandArea` over `DepthArea`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#64]
The depth area covers the entire chart; applies to multiple datasets. Example from 101AA005C1AB1.000 ed2:

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/edbadd53-8501-4bc8-9bcf-55750cee6f68)

**Comment by kusala9** [comment]
I'm fairly sure these are all caused by the conversion (and subsequent mods) of NEWOBJ Polygons in the original Chart1. Chart 1 contained a LOT of NEWOBJ objects which were used to show particular portrayal patterns without needing to explicitly refer to objects. These got converted (initially) to AISAidToNavigation (because that's the default mapping for NEWOBJ. subsequently we blanket modified these to LandArea which works well for some (points and curves) but not for the polygons because it messes up the topology :( - Longer term (and we're reviewing these now) all the old NEWOBJ will have to be replaced with something meaningful, either features which have the desired portrayal, or some other variant that performs the same job it did in S-57.

Unless these are a problem for portrayal testing we can leave them and they'll gradually be picked up as the cells are reviewed and edited to align with Chart 1 properly. 

I've fixed AB1 anyway but understand there will be lots more of these. In the interim as we edit these we can turn them into SeaAreaNamedWaterArea and set a name which contains the required S-57 pattern.

**Comment by DavidGrant-NIWC** [comment]
Sounds good, feel free to close the issue. If there isn't already a validation check for the topology issue then you might want to consider adding one: https://github.com/iho-ohi/S-101-Validation/issues
