### ISSUE TITLE
Overlapping scale bands in Chart 1

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#99]
I don't believe the datasets (specifically the `DataCoverage` features) are encoded so that they will display correctly when loaded in the ECDIS. There are overlapping scale ranges.

|MSVS|Result|
|:---:|:---:|
|1:45k|![image](https://github.com/user-attachments/assets/b9227772-e66e-422b-86bb-c2b0cf886bfb)|
|1:90k|![image](https://github.com/user-attachments/assets/7d47956c-98e4-41f2-99ae-ae1770eaf4d2)|

_Originally posted by @DavidGrant-NIWC in https://github.com/iho-ohi/S-164-Sub-Group/issues/45#issuecomment-2344336093_

**Comment by kusala9** [comment]
Mine seem to show all the cells when the MSVS is 45k? Is this from the S-164 repository? The Bottom Left cell will need to be either changed (to something more appropriate) or deleted I think. The larger scales should all come in at 45k. Need to check with original Chart 1 because I remember a comment in the review meetings that the CSCL should be set to 50k to fill a standard screen. this needs to be looked into.

![image](https://github.com/user-attachments/assets/d72d3806-0080-4eb5-8d21-e8eb5cfb674b)

**Comment by DavidGrant-NIWC** [comment]
Check your chart library page and see if you have the XMS dataset loaded:

![image](https://github.com/user-attachments/assets/0a7d37a6-2e4e-49cc-9577-e59cac5a8cf7)

**Comment by kusala9** [comment]
i thought this was a weird bug in the ShoreECDIS but I believe it's because there's a stray cell in the distribution. Delete ***YNT.000 and reinstall from github - should all work. All the larger scales should come in at 45k
